import { Metadata } from 'next';
import { Page } from './component';

export const metadata: Metadata = {
  title: "openpgpjs-performance",
  description: "Generated by create next app",
};

export default function Home() {
  return <Page />
}
